### ISSUE TITLE
Unexpected change to server model in benchmark

### ISSUE THREAD

**Issue by LuckMonkeys** [JonasGeiping/breaching#3]
Hi

In `breaching.analysis.report()` function, it directly uses the `server.model` to load the parameters and buffers. However, this may cause wrong modification to `server.model` and influences the next run in benchmark. It may be possible to resolve the problem by adding `model=copy.deepcopy(model)` before `model.to(**setup)`

```python
    model = copy.deepcopy(model)
    model.to(**setup) 
```

**Comment by JonasGeiping** [comment]
I didn't have this issue so far, but a fix is now included, just in case: https://github.com/JonasGeiping/breaching/commit/406135172a65408a0d4ab77eca7c39f03b5baf82.

Thanks for sharing!
