### ISSUE TITLE
Examples for text + classification task

### ISSUE THREAD

**Issue by phfaustini** [JonasGeiping/breaching#7]
All text examples cover MLM task. What should I do to, for example, run an attack against Bert in a classification task using the Cola dataset?

I tried to change the **[Decepticons - Analytic Attack - BERT on Wikitext.ipynb](https://github.com/JonasGeiping/breaching/blob/main/examples/Decepticons%20-%20%20Analytic%20Attack%20-%20BERT%20on%20Wikitext.ipynb)** example by adding

```python
cfg.case.data.name = 'cola'
cfg.case.data.task = 'classification'
```

But then when I run it I get the following error when the dataset is loaded

```
raw_dataset = Dataset.from_dict({k: [v] for k, v in raw_datapoint.items()})
AttributeError: 'Dataset' object has no attribute 'items'. Did you mean: 'iter'?
```

Is there something else I need to set?

**Comment by JonasGeiping** [comment]
A first step would be to load the whole cola config group, via `case=cola`. Does that get you somewhere?

**Comment by phfaustini** [comment]
Hi Jonas, thanks for the reply,

I included the "case/data=cola", but I got the same error. It was simple to solve, though. The reason is that 
` load_dataset("glue", "cola")` already returns a Dataset. Thus, I changed, for now, in [dataset_texts.py](https://github.com/JonasGeiping/breaching/blob/main/breaching/cases/data/cached_dataset.py)

```python
raw_dataset = Dataset.from_dict({k: [v] for k, v in raw_datapoint.items()})
```

to 

```python
raw_dataset = raw_datapoint  # It is already a Dataset
```

**However**, I face later something I have no idea how to solve or tweak. The following assert in [base_attack.py](https://github.com/JonasGeiping/breaching/blob/main/breaching/attacks/base_attack.py) fails 

```python
assert len(bias_per_query[0]) == server_payload[0]["metadata"]["vocab_size"]
```

The `bias_per_query[0]` has length 768 (hidden layer size), whereas it was expecting 30522 (Bert's vocabulary size). If I comment the line (which I think is wrong), the code runs till the end, but all the tokens are predicted as CLS, so I think I should tweak something else. By any chance, would have any idea?

**Comment by JonasGeiping** [comment]
This is a problem, your `decoder_bias_parameter_idx ` should be `None`, to indicate that your model does not have a decoder bias for every token (as it ends with a classification head). Also, make sure that `embedding_parameter_idx` points to the correct entry in the list of gradients, corresponding to the weights of the token embedding.

**Comment by JonasGeiping** [comment]
As a sanity check, you could also set `token_strategy` to None, which should be an okaish baseline, where no token info is used, and all found embeddings are matched against the full vocabulary.

**Comment by JonasGeiping** [comment]
Closing this for now. Let me know if you have more questions.
