### ISSUE TITLE
Getting positions

### ISSUE THREAD

**Issue by shanefeng123** [JonasGeiping/breaching#8]
Hi,

Thanks for providing the implementation for DECEPTICONS: CORRUPTED TRANSFORMERS BREACH PRIVACY IN FEDERATED LEARNING FOR LANGUAGE MODELS. 

I tried to look for the code in where they extract the positional information for the extracted tokens but with no luck. Can you please help me point out where is it? Thanks a lot.

**Comment by JonasGeiping** [comment]
https://github.com/JonasGeiping/breaching/blob/a51fba6b637207adbfbbde3a117eed2391c515ce/breaching/attacks/analytic_attack.py#L279

Best, 
Jonas

**Comment by shanefeng123** [comment]
Thanks.
